### ISSUE TITLE
packages security vulnerability 

### ISSUE THREAD

**Issue by orenyodfat** [daostack/migration#118]
![Screen Shot 2019-04-14 at 11 37 57](https://user-images.githubusercontent.com/5994398/56090348-fc7c4f80-5ea9-11e9-895c-757024e9934a.png)

**Comment by jellegerbrandy** [comment]
as you know, this implies upgrading the ganache docker image.
Can we do this? The warnings are all the way up the stack, and they are making me nervous :)

**Comment by orenyodfat** [comment]
Still waiting for ganach core to be fix to be able to work with new web 3
