### ISSUE TITLE
Trying to execute test boosted proposal breaks subgraph

### ISSUE THREAD

**Issue by tibetsprague** [daostack/migration#123]
I think this must be a migration issue but when i try to execute/redeem (by calling Redeemer.redeem) the test DAO's boosted test proposal I get the following error:

`graph-node_1          |   Apr 17 18:37:44.112 ERRO Subgraph instance failed to run: Failed to process event: Failed to handle Ethereum event with handler "handleRedeemReputation": Trap: Trap { kind: Host(HostExportError("Mapping aborted at src/types/schema.ts, line 5222, column 4, with message: Cannot save GPReward entity without an ID")) }, id: QmQx56vmb9vsihXsbjbqYE8yVY33P1QKeNj2zCxJKjr2tM`

And then the subgraph stops working

**Comment by orenyodfat** [comment]
it looks like subgraph issue which is solved by : 
https://github.com/daostack/subgraph/pull/190
