### ISSUE TITLE
include "real" daos in the docker images

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/migration#124]
It would be good if we could, during development, test with real examples. 
In particular, we should include:

- the GenesisDAO
- the DutchX DAO

The dutchx dao is especially important and relatively urgent, because we need to be able to develop all the specific dxDAO actions in Alchemy.

**Comment by jellegerbrandy** [comment]
also for rinkeby!

**Comment by ben-kaufman** [comment]
@jellegerbrandy @orenyodfat I would need a `migration-params.json` file for the DutchX DAO in order to deploy it.

**Comment by orenyodfat** [comment]
you can find it [here]( https://github.com/gnosis/dx-daostack/blob/master/deployment_logs/deployment-mainnet-test-07may.txt#L182 ) ,
 [here](https://github.com/gnosis/dx-daostack/blob/master/deployment_logs/deployment-mainnet-test-07may.txt#L203) 
and 
 [here](https://github.com/gnosis/dx-daostack/blob/master/deployment_logs/deployment-mainnet-test-07may.txt#L224) 

though I am not sure , what does it means "real daos" ...

**Comment by jellegerbrandy** [comment]
We are developing modules in alchemy that need to work with the dxDAO, and to develop these modules I need docker images (and a staging environment) that I can test again. So we need a docker iamge sith the dxDAO deployed on it. 

I do not know "why the migration repo need to support specific daos" - perhaps you have doubts about where to store this code. 

But I do know is that we need a testing and staging environment that is very similar to the production environment - i.e. "real daos" :-)

**Comment by orenyodfat** [comment]
we can try to generalised that : 
- a Dao with 3 schemes  - generic action, schemeregistar, contribution reward.
- all schemes will have the same parameters ? same as the fast Dao ?
- a mock ownable contract ,which will be owned by the Dao avatar and will be used to test the generic action.

**Comment by orenyodfat** [comment]
we (@jellegerbrandy and @orenyodfat ) decided to use existing actionmock to be used as a test env for testing the genericscheme in alchemy.

in addition we will have a "real" Dutchx contract at Rinkeby - the test Dao will be set as its auctioneer .

so for now , no need to change the migration.,
