### ISSUE TITLE
Arguments mnemonic and private-key are mutually exclusive

### ISSUE THREAD

**Issue by dkent600** [daostack/migration#14]
When I run this in my OS shell:

node ./migrate.js --provider "https://kovan.infura.io/[...]" --mnemonic "[...]" --output "[...]/migration.json"

I get this:

"Arguments mnemonic and private-key are mutually exclusive"

**Comment by tsuberim** [comment]
This is because of the default `privateKey`. Need to allow `mnemonic` to override `privateKey` and remove the mutual exclusion.
