### ISSUE TITLE
register serveral genericSchemes at the test DAO

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/migration#140]
Given that we generate different interfaces for different genericScheme contracts, it would be convenient if we had different GenericSchemes on the test DAO (so we can test these side-by-side).

**Comment by ben-kaufman** [comment]
Which contract(s) should the other GenericScheme(s) target?

**Comment by tibetsprague** [comment]
My understanding is that one of them should target ActionMock as we will use that contract as a test of the DutchX actions in alchemy. The other can target anything...? Though it would be nice if the contract hadn’t functions we could actually execute and call.

**Comment by jellegerbrandy** [comment]
The important thing is that we have more than one genericScheme in our test
DAO.

The actionmock is pretty good as a  test model for different cases of
generic actions.

For our dxDAO module, it would be nice to have a target contract that
implements the dutchX ABI (at least teh functions we are calling). But this
is not strictly necessary,  we're ok without it - a second deployment of
the ActionMock would already be fairly good.

**Comment by ben-kaufman** [comment]
You mean more than on Generic Scheme parameters set, no need for to separate GS contract right?
