### ISSUE TITLE
add a "dxDAO" DAO to the test ganache 

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/migration#146]
And subsequently index it in the test subgraph..

What this means in practice is to deploy a dao called "dxDAO" that has GenericScheme (as described in https://github.com/daostack/subgraph/issues/261)

**Comment by ben-kaufman** [comment]
I'm not sure this should really be part of the migration repo... Also I need all the contracts and specifications if we do add it.

**Comment by jellegerbrandy** [comment]
does not need to be the comlete dutchx contract, just a DAO called "dxDAO" that has a generic scheme attached to it. 

Just as good for our tests, and easier to do: add a second "GenericScheme" to the "test" DAO, so we can test the dutchx functionality on that

**Comment by ben-kaufman** [comment]
Which contract should the generic scheme call?

**Comment by jellegerbrandy** [comment]
it does not matter, any contract is fine.

We are now doing a kind of hack to run our tests, but this turns out to break on updates of the migration repo, so if you can give this prio, it would save us some hour of debugging after each update :-)

**Comment by ben-kaufman** [comment]
I'm not sure I understand what you need here. We already have a GenericScheme connected to the test DAO, why is it necessary to have 2?

**Comment by jellegerbrandy** [comment]
Because there are two cases to test: the dtuchX generic Scheme, and the
"normal" generic scheme, which have different interfaces.
