### ISSUE TITLE
Can we have a test DAO that has 100s of proposals in the history and 100s of reputation holders?

### ISSUE THREAD

**Issue by tibetsprague** [daostack/migration#153]
To test loading on scroll

**Comment by orenyodfat** [comment]
not sure it should be part of the migration repo.
you can create one on the fly.

**Comment by jellegerbrandy** [comment]
yes we could, in theory. 

But the point of providing images for testing (like these https://hub.docker.com/r/daostack/subgraph-postgres/tags) is that we do NOT have a write code in our tests to create daos and proposals and users and members etc.   Why provide 4 different daos and 10 different proposals and 10 rep holders, but not 100?

**Comment by orenyodfat** [comment]
there is a already a separate dedicated repo for any custom test dao environment needs.
https://github.com/daostack/test_env
