### ISSUE TITLE
Need a working redeemer contract

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/migration#164]
For redeeming Expired proposals form pre-rc.21 versions, we need a redeemer contract that works with those versions. 

cf. https://github.com/daostack/migration/issues/163

**Comment by ben-kaufman** [comment]
I'm not sure I fully understand this issue, we still have all previous redeemers for pre 21 versions. Are you sure this issue is related to the migration?

**Comment by orenyodfat** [comment]
use https://github.com/daostack/arc/releases/tag/0.0.1-rc.22
this include a new redeemer which gets the contributionRewards and genesisProtocol as parameters to redeem function.
