### ISSUE TITLE
Add to readme about custom contracts

### ISSUE THREAD

**Issue by dkent600** [daostack/migration#166]
The ability to do something with "custom contracts" was added here, but there is no description for what that really means and how the user can do it.  There should be something in the readme.

https://github.com/daostack/migration/pull/162/files

**Comment by ben-kaufman** [comment]
Already added it here:
https://github.com/daostack/migration/commit/c3eb4cc716b4ba05fafb4c88b1f8ae3ad183c6fe#diff-04c6e90faac2675aa89e2176d2eec7d8
