### ISSUE TITLE
Sanitize dao-params.json Before Deployment

### ISSUE THREAD

**Issue by dOrgJelli** [daostack/migration#171]
During deployment, a genesis protocol parameter was misnamed, and this error was not found until very late in the deployment process.

The migration script should fully sanitize the params.json file before it begins deploying to avoid as many late stage errors as possible.

**Comment by dkent600** [comment]
JSON can be made to conform to a "schema" with tools to validate that it confirms against the schema.

**Comment by dOrgJelli** [comment]
@dkent600 definitely. Would be great of there was a "params-schema.json" file at the root of the repo, and a package such as this one could be used to verify the input params.json complies.

https://www.npmjs.com/package/jsonschema
