### ISSUE TITLE
deploy a new DAO with the tokenforreputationcontract on rinkeby and index it

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/migration#174]
Result:
- a new DAO with TokenForReputation registered to it
- Index this in the subgraph (meaning: the DAO should be in the daos collection, the TokenForReputation  contract should be in the contractInfos collection)
- Please talk to Alex about the token distribution specs (which accounts can claim the reputation)
- Please use the latest version of arc that includes this fix: https://github.com/daostack/arc/commit/20eb4106035eb5b1fc17964dbb3f8f2dd8bb5371

**Comment by A-Zak** [comment]
@ben-kaufman for the token distribution, can we just connect it to the gen token address so we'd have something to test with?

**Comment by ben-kaufman** [comment]
Closing for now as I think it was addressed already, please reopen if this is still relevant.
