### ISSUE TITLE
migrate base hangs migrating to rinkeby

### ISSUE THREAD

**Issue by dkent600** [daostack/migration#19]
I submitted "https://rinkeby.infura.io/UeW8cwaou03qFgsAHoDP" as a provider to migrate.  The result:  The script hanged on "\ Migrating DAOToken...".  

The script should report an error and return to the shell.

**Comment by dkent600** [comment]
It actually eventually does return, with the message:  "Transaction was not mined within750 seconds, please make sure your transaction was p"  (it is truncated in my shell)

**Comment by tsuberim** [comment]
@dkent600  Can we close this?
