### ISSUE TITLE
Handle "Error: Transaction was not mined within 50 blocks..."

### ISSUE THREAD

**Issue by dOrgJelli** [daostack/migration#211]
Currently the migration script doesn't handle the case where web3.js' retries exceeds 50 tries. You can read more about this issue here:
https://github.com/ethereum/web3.js/issues/1102

I foresee this issue being resolved along with this one within the same change-set:
https://github.com/daostack/migration/issues/206

**Comment by yangwao** [comment]
Looking forward, you are doing great work 🤗

**Comment by dOrgJelli** [comment]
I think this might be the way to go about handling this @ben-kaufman https://github.com/ethereum/web3.js/issues/1102#issuecomment-357265249
