### ISSUE TITLE
Don't use a deploymentState from another network

### ISSUE THREAD

**Issue by dOrgJelli** [daostack/migration#229]
Store the network name in the deployment state. If you detect the stored state is from another network, warn the user and ask if they'd like to clear state and restart on the new network.

**Comment by ben-kaufman** [comment]
Good idea, though I think it would be even better to just pass the network name in the `getState()` and `setState` functions. This way we can have states for multiple networks and in any case won't need to bother the user about a state which is irrelevant to his current network. What do you think?

**Comment by ben-kaufman** [comment]
I implemented it [here](https://github.com/daostack/migration/pull/230), please take a look and let me know if that solves the issue well for you.

**Comment by dOrgJelli** [comment]
Yes I think that makes a lot of sense for the deployment state, as you can't possibly continue a deployment on another network :P
