### ISSUE TITLE
using old beta version of web3

### ISSUE THREAD

**Issue by dkent600** [daostack/migration#296]
migrations is using an old beta version of web3.  falling way behind.

**Comment by ben-kaufman** [comment]
We already use the latest web3:
https://github.com/daostack/migration/blob/ea0c8dbea953ce8af315b0a234068dee240b7589/package.json#L64

**Comment by dkent600** [comment]
ok cool, I guess it just hasn't floated its way up to alchemy yet.

**Comment by dkent600** [comment]
> We already use the latest web3:
> https://github.com/daostack/migration/blob/ea0c8dbea953ce8af315b0a234068dee240b7589/package.json#L64

@ben-kaufman I see the change has been made, but I don't see that this has ever been deployed.  Am I missing something?

**Comment by ben-kaufman** [comment]
Just released `0.0.1-rc.41-v2` with this change
