### ISSUE TITLE
Supply a constant "networkId" to ganache

### ISSUE THREAD

**Issue by dkent600** [daostack/migration#30]
Supply a constant "networkId" to ganache. This would enable people to identify the network as coming from the migration repo. Arc.js has been using an id of "1512051714758", and it would be good to adopt that, again, for consistency across releases.

**Comment by dkent600** [comment]
BTW, it is possible a constant networkId will help with stability of the ganache DB.

**Comment by jellegerbrandy** [comment]
:+1: I tried to do thsi by passing  `--networkId` parameter when starting ganache, but it does not seem to have any effect...

**Comment by dkent600** [comment]
@jellegerbrandy It is the mnemonic that gives you the constant addresses, not the networkId.  Supplying the  networkId just sets the networkId  :-)
