### ISSUE TITLE
Latest migration release (0.0.1-rc.7-v1) did not migrate to kovan.

### ISSUE THREAD

**Issue by dkent600** [daostack/migration#46]
Latest migration release (0.0.1-rc.7-v1) did not migrate to kovan.

**Comment by ben-kaufman** [comment]
Are you sure? Most Kovan addresses didn't change because the code for the contracts was the same in both Arc versions. Rinkeby was updated because it was not migrated with the latest contracts.

**Comment by dkent600** [comment]
> Rinkeby was updated because it was not migrated with the latest contracts. 

You mean RInkeby was not updated in the previous release of the migraiton repo (Arc.rc.6)?

> Most Kovan addresses didn't change because the code for the contracts was the same in both Arc versions

For Kovan the only change is for Redeemer, haven't checked as to why.  I guess that is OK then.
