### ISSUE TITLE
Add some mock scenarios scripts

### ISSUE THREAD

**Issue by tsuberim** [daostack/migration#5]
Scripts for simulating activity in the example DAO (proposing, boosting, etc..).

**Comment by jellegerbrandy** [comment]
yes this would be useful. 
We are doing this kind of setup in subgraph and alchemy and arc.js, and now in this repo, and we will need it in the client repo. 
I think that (as soon as we can) these scripts should be based on the client lib (which is the place to cofify how to add a proposal etc). This would be better both to avoid duplicating code as well as we'll "eat our own dog food" by using the client lib.
