### ISSUE TITLE
The founders tokens and reputation need to be in WEI

### ISSUE THREAD

**Issue by tibetsprague** [daostack/migration#64]

**Comment by ben-kaufman** [comment]
I think making it in Gwei is much more convenient to use. I don't really see why when initializing DAO you'd need to use wei units...

**Comment by tibetsprague** [comment]
well we could use Gwei we just need to pick something and stick with it, and we just did a whole bunch of work in the client and alchemy to expect all units to be in Wei

**Comment by tibetsprague** [comment]
Hmm, actually it looks like these are bring converted into wei, so there shouldnt be an issue, let me see whats going on. The total values just look too small in Alchemy...

**Comment by tibetsprague** [comment]
nevermind, this one is fine
