### ISSUE TITLE
Test DAO should have a DAO threshold const (and other params) that makes sense

### ISSUE THREAD

**Issue by tibetsprague** [daostack/migration#70]
Right now it seems too small at 2000, does it need to be in WEI?

**Comment by ben-kaufman** [comment]
How much would you like it to be?

**Comment by tibetsprague** [comment]
Whatever it should be be in real life. @A-Zak  you have these numbers?

**Comment by jellegerbrandy** [comment]
@A-Zak @ben-kaufman this is important to fix quickly as it is blocking the testing somewhat.

**Comment by ben-kaufman** [comment]
Ok, I just need to know the correct parameters.

**Comment by A-Zak** [comment]
I have the doc that describes the parameters that of the real genesis dao. I've created a tab with overrides for the test dao... 

@tibetsprague @ben-kaufman - are these the params that you need?

https://docs.google.com/spreadsheets/d/1fkybRjRR4rO53gkpEhwA3Q2UjAlkIe3q7rrs0_bZFqI/edit#gid=1264434596

**Comment by ben-kaufman** [comment]
@A-Zak thanks, I understand some of the parameters there but not sure about others. Could you please send the correct test parameters in the following format:
```
{
    boostedVotePeriodLimit: 600,
    daoBountyConst: 75,
    minimumDaoBountyGWei: 100,
    queuedVotePeriodLimit: 600,
    queuedVoteRequiredPercentage: 50,
    preBoostedVotePeriodLimit: 600,
    proposingRepRewardGwei: 5,
    quietEndingPeriod: 300,
    thresholdConst: 2000,
    voteOnBehalf: '0x0000000000000000000000000000000000000000',
    votersReputationLossRatio: 1
  }
```
@tibetsprague do you need this only for the Ganache test DAO or also for the DAO deployment on other networks?

**Comment by tibetsprague** [comment]
We will want the expiration periods to be short on the test net daos too I think.

**Comment by A-Zak** [comment]
@leviadam, @orenyodfat, can you please help with this?
I'm not sure about some of these params... /:

**Comment by orenyodfat** [comment]
2000 might be ok for tests .
Dx dao use values of 1200 and 1300 which also be good for tests.
The value not suppose to be in wei units .
Please note that this value is devided by 1000 by the contract ...
So a value of 2000 output an Alpha as 2.
A value of 1300 output an Alpha value of 1.3 .
The dao threshold = Alpha ^(number of booted proposals)
Alpha is the base of the exponent

**Comment by A-Zak** [comment]
@ben-kaufman I think these should work, can you confirm that they make sense... :)

{
    boostedVotePeriodLimit: 600,
    daoBountyConst: 10,
    minimumDaoBountyGWei: 100,
    queuedVotePeriodLimit: 1800,
    queuedVoteRequiredPercentage: 50,
    preBoostedVotePeriodLimit: 600,
    proposingRepRewardGwei: 5,
    quietEndingPeriod: 300,
    thresholdConst: 2000,
    voteOnBehalf: '0x0000000000000000000000000000000000000000',
    votersReputationLossRatio: 1
}
