### ISSUE TITLE
Test DAOs should have different names

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/migration#72]
this is too confusing:
![image](https://user-images.githubusercontent.com/1306173/53575007-fc7df580-3b70-11e9-8ab5-30d1f53de8a7.png)

**Comment by ben-kaufman** [comment]
So should I just generate some random ID for the name?

**Comment by jellegerbrandy** [comment]
Yeah, why not. Something cool like this maybe? https://jsfiddle.net/katowulf/3gtDf/
