### ISSUE TITLE
Test proposals have no title

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/migration#79]
I realize this is a bit difficult to do in the migration repo, but it would definitly improve the experience :-)

It would basically mean doing what is done here in the client lib: https://github.com/daostack/client/blob/master/src/proposal.ts#L132

**Comment by ben-kaufman** [comment]
What I'm not sure about with that is how to connect the migration to use the same ipfs network the subgraph uses.

**Comment by jellegerbrandy** [comment]
Yes, neither do I. The only thing that comes to mind is a bit of a fragile
hack, where the migration repo saves a file with IPFS hashes and the
correspnoding data, and when we build the subgraph containers, we add those
data to IPFS there.  Not very elegant, that. Let's think about it some more
:-)

**Comment by tibetsprague** [comment]
When we figure this out we also need descriptions and URLs for the test proposals

**Comment by jellegerbrandy** [comment]
I'm closing this as (1) do not see hwo to do this and (2) we can (and do) create proposals with titles in the tests themselves, sowe really do not need this so much.

**Comment by ben-kaufman** [comment]
This issue was handled in the `test-env` repo, closing here.
