### ISSUE TITLE
npm install --global @daostack/migration fails

### ISSUE THREAD

**Issue by dkent600** [daostack/migration#85]
When I run `npm install --global @daostack/migration` as instructed by the README, it fails with the error:

> gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@daostack/migration/node_modules/keccak/build'
gyp ERR! System Linux 4.4.0-17763-Microsoft
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/@daostack/migration/node_modules/keccak

This is running under `sudo`, in a bash shell.  Running the same command in a Windows shell works fine.

**Comment by dkent600** [comment]
Then when I run `daostack-migrate base --version`, in a bash shell, I get:  

> /mnt/c/Users/dkent/AppData/Roaming/npm/node: 1: /mnt/c/Users/dkent/AppData/Roaming/npm/node: /node_modules/node/bin/node: not found

**Comment by orenyodfat** [comment]
Fail for me in macOS ..both with or without sudo .

**Comment by ben-kaufman** [comment]
@dkent600 please see: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally it worked for @orenyodfat

**Comment by dkent600** [comment]
Would be nice to include this link in the README file

**Comment by ben-kaufman** [comment]
Ok.

**Comment by orenyodfat** [comment]
well , this link solve this specific issue ..though cause any npm --global install package to not include automatically include in the path.. @ben-kaufman add that also to the readme

**Comment by dkent600** [comment]
OK, installing 'nvm' (an npm version manager) plus upgrading my version of 'git' (`sudo apt-get upgrade git  --fix-missing`) got it to succeed.
