### ISSUE TITLE
migration script does not migrate the Infra contracts

### ISSUE THREAD

**Issue by dkent600** [daostack/migration#86]
Running `daostack-migrate base --force` does not migrate the Infra voting machine contracts.  I just ran this against kovan.  Here is the output:

>  Network:      kovan
i Account:      0x1bf4e7D549fD7Bf9c6BA3Be8BD2b9Af62F086220
i Balance:      15.121912564622604268ETH
i Gas price:    1GWei
i Found an existing previous migration file (./migration.json)
i 0x8dffad51a0b9b4988938306844960680a0c41b57b559753a1d449800184694c2 | 0.00446 ETH | 0x1Ccc6959A99d68A991D76dDea3aF15572FA51706 => ControllerCreator
i 0x47d589a9dec27f86d22a55ef0178a18946cfa56aa3816dd39b8c33c39ddea885 | 0.00451 ETH | 0xa42C4D23488070c5D209522d189eFc23993A2B22 => DaoCreator
i 0xdeb4826864d88d99123e69d8dda9d32e8598754bfbfc1e580ae11bab15e0fc78 | 0.00510 ETH | 0x4e7D05CFB0B1E566D3e8EB5BE158CAFc11666e63 => UController
i 0xabe5f34598ddf4e10a4be1db32289451d83bfaf3aa8b6d3ec23959ebb0107222 | 0.00212 ETH | 0xb0a3707DeD97C588eA72bA4BF996D725674Bd583 => SchemeRegistrar
i 0x8544aee47277cf83cc50c5b21a1162df7e84375203e2f220edf35209ab7bb0a4 | 0.00206 ETH | 0xD743e927ac5fE21806449e04787e67616ea48989 => UpgradeScheme
i 0xed56559dd60da012f3a1e18008264782c15c910a20fae61a40754c22f2ec8008 | 0.00215 ETH | 0x97531506a6a6010579F5b920334a11F82298ac72 => GlobalConstraintRegistrar
i 0xce97e1f376851c261aebc5d61ce74e905b161505b98cc9ffd8be2d94644dae70 | 0.00343 ETH | 0xAabF305D95dB51B5933eB923b23835C11dbCbD91 => ContributionReward
i 0x9f058d8b21dcd6aad1e38f2d95b1423085a762e0330104baae3760dea9307af4 | 0.00030 ETH | 0x59CDFbD82A90C889BddE79436DC2e57fb04b931f => TokenCapGC
i 0xcdf845bc5b873573ad1151726a8b8c2c14d628d1c7bb44abdf0bcf9a01da4779 | 0.00309 ETH | 0xE3d50f0364559A8424317F2c9a58746ca8863105 => VestingScheme
i 0x0a90d7dd00eea6a6cd32a9b998100eab921b826d11859eca16342d4b395d723c | 0.00202 ETH | 0x7abb191148513d76A9633BE9aFd5092c2cc1C3B5 => VoteInOrganizationScheme
i 0x5899d22f81863253f01043ee9ef760d3a51daf35a57d17a7dc36baa7edf1d9d7 | 0.00086 ETH | 0x1Fff840ABB8AE60dA199809E9D019152Acef011a => OrganizationRegister
i 0x3f089863dc4fd375f5efd610373dc81c6b769fd602d0d1cb028b2a7cb303203d | 0.00093 ETH | 0x14ed9d83d177b0c1750A9A967aff894EB795CAEd => Redeemer
i 0x3e2051bebb4163a643f2ad03472f47abf6e404112c9b1a189b9014aaff5a5978 | 0.00221 ETH | 0x8fc499345E4d21d16aa2Ea41503f338c70CF22Be => GenericScheme
i Finished in 6 minutes and costed 0.033240388ETH
√ Wrote results to ./migration.json.

**Comment by orenyodfat** [comment]
migration script migrates only updated contracts.

**Comment by dkent600** [comment]
My understanding is that if I provide `--force` (which I did) then the script is supposed to deploy all contracts regardless of whether they have been updated.  But it didn't in the case of the Infra contracts.

**Comment by ben-kaufman** [comment]
@dkent600 no. `--force` will just disable the confirm prompt and instead will use the default response to it (which is `false` for redeploying a contract), and will use `true` if there is no default answer.

**Comment by dkent600** [comment]
@ben-kaufman Is there any way in the CLI to force contract _re-_migration?

**Comment by ben-kaufman** [comment]
I don't think so. You can just delete the `migration.json` file or specify an empty one to make sure it doesn't use the old addresses.

**Comment by dkent600** [comment]
ok, I guess the only thing I might suggest would be to be clear in the docs that "force" doesn't really force anything (which is counter-intuitive, thus the utility in documenting clearly).

**Comment by dkent600** [comment]
But frankly, I think that the default for `--force` should in fact be `true`.  Then this option would do what people expect it to do.
