### ISSUE TITLE
Need option to specify previous migration and have correct default

### ISSUE THREAD

**Issue by orenyodfat** [daostack/migration#89]
daostack-migrate dao --params ./daostack/daostack2/migration/migration-params-oren.json --gasPrice 5 --provider https://kovan.infura.io/xxxxxxxxxxxxxx --private-key 0xxxxxxxxxxxxxx
:information_source: Network:     kovan
:information_source: Account:     0xB0C908140FE6FD6FBd4990A5c2e35ca6Dc12bFB2
:information_source: Balance:     1.823381951313ETH
:information_source: Gas price:     5GWei
? About to migrate new DAO. Continue? Yes
:heavy_multiplication_x: Couldn't find existing base migration ('migration.json' > 'base').
Error: Couldn't find existing base migration ('migration.json' > 'base').
    at migrateDAO (/Users/oren/.npm-global/lib/node_modules/@daostack/migration/migrate-dao.js:11:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
➜  ~

daostack-migrate --version
0.0.1-rc.12-v6

**Comment by orenyodfat** [comment]
absolute path works.

**Comment by ben-kaufman** [comment]
It shouldn't be related to the `migration-params.json` but to the `migration.json` which should already exist inside the package. I'm checking that.
