### ISSUE TITLE
migration cli - should show deployed contracts addresses on terminal during execution

### ISSUE THREAD

**Issue by orenyodfat** [daostack/migration#92]

**Comment by ben-kaufman** [comment]
Not sure what you mean here.

**Comment by orenyodfat** [comment]
The new deployed contracts addresses (avatar,token,reputation,controllers) should be log to the terminal during the execution ..regardless of the migration.json which is written at the end.

**Comment by orenyodfat** [comment]
This issue is still not fixed.
